### ISSUE TITLE
Running reference value server at high frequency

### ISSUE THREAD

**Issue by whizkidrohan** [Parrot-Developers/RollingSpiderEdu#42]
I'm trying to implement aggressive maneuvers on the rolling spider using an external motion capture system. I plan to run a position controller on a pc which would send the reference attitude to the quadrotor at around 50-100hz. I tried modifying the reference value server to send desired attitude but I'm running into packet-loss and latency issues even at a frequency of 10hz (with the optical flow disabled). Any advice on the best way to implement this?

**Comment by friether** [comment]
I am afraid that this might not work with the current setup since it is a very crude one (establishing a socket-connection in "controls-code"; also, Parrot's code parts that run in the background obviously already do some communication, and we still build this crude part on top.
[#27](https://github.com/Parrot-Developers/RollingSpiderEdu/issues/27) might improve the current implementation.
Parrot had an API for the Rolling Spider somewhere that does not allow you to control motor speeds directly, but maybe the orientation. I would recommend looking into that.
Sorry for being that vague.
